/// Plain-text incident report for email (readable by non-engineers).
String formatIncidentEmailBody(Map<String, dynamic> incident) {
  final Map<String, dynamic> event =
      incident['event'] as Map<String, dynamic>? ?? <String, dynamic>{};
  final Map<String, dynamic> app =
      incident['app'] as Map<String, dynamic>? ?? <String, dynamic>{};
  final Map<String, dynamic> user =
      incident['user'] as Map<String, dynamic>? ?? <String, dynamic>{};
  final Map<String, dynamic>? device = incident['device'] as Map<String, dynamic>?;
  final Map<String, dynamic>? connectivity =
      incident['connectivity'] as Map<String, dynamic>?;
  final Map<String, dynamic> screen =
      incident['screen'] as Map<String, dynamic>? ?? <String, dynamic>{};
  final Map<String, dynamic> network =
      incident['network'] as Map<String, dynamic>? ?? <String, dynamic>{};

  final StringBuffer body = StringBuffer()
    ..writeln('MOBILE INCIDENT REPORT')
    ..writeln('========================')
    ..writeln()
    ..writeln('Summary')
    ..writeln('--------')
    ..writeln('Incident ID : ${incident['incidentId']}')
    ..writeln('Time (UTC)  : ${_timeUtc(incident)}')
    ..writeln('Time (local): ${_timeLocal(incident)}')
    ..writeln('Severity    : ${event['level']}')
    ..writeln('Category    : ${event['category']}')
    ..writeln('Message     : ${event['message']}')
    ..writeln()
    ..writeln('Application')
    ..writeln('-------------')
    ..writeln('Package     : ${app['packageName']}')
    ..writeln('Version     : ${app['version']} (${app['buildNumber']})')
    ..writeln('Flavor      : ${app['flavor']}')
    ..writeln('SDK         : ${app['sdkVersion']}')
    ..writeln('Platform    : ${app['platform']}')
    ..writeln()
    ..writeln('User')
    ..writeln('----')
    ..writeln('User ID     : ${user['userId'] ?? '—'}')
    ..writeln('Session ID  : ${user['sessionId'] ?? '—'}');
  final Map<String, dynamic>? userMeta = user['metadata'] as Map<String, dynamic>?;
  if (userMeta != null && userMeta.isNotEmpty) {
    body.writeln('User meta   : $userMeta');
  }
  body.writeln();

  if (device != null) {
    body
      ..writeln('Device')
      ..writeln('------')
      ..writeln('Model       : ${device['manufacturer']} ${device['deviceModel']}')
      ..writeln('OS          : ${device['osVersion']}')
      ..writeln('RAM used    : ${device['ramUsedBytes']} bytes')
      ..writeln('RAM free    : ${device['ramFreeBytes'] ?? '—'}')
      ..writeln('Battery     : ${device['batteryLevel'] ?? '—'} (${device['chargingState'] ?? device['batteryState'] ?? '—'})')
      ..writeln('Thermal     : ${device['thermalState'] ?? '—'}')
      ..writeln();
  }

  if (connectivity != null) {
    body
      ..writeln('Connectivity')
      ..writeln('--------------')
      ..writeln('Online      : ${connectivity['isOnline']}')
      ..writeln('Types       : ${(connectivity['types'] as List<dynamic>?)?.join(', ') ?? '—'}')
      ..writeln();
  }

  body
    ..writeln('Screen / user flow')
    ..writeln('------------------')
    ..writeln('Current     : ${screen['currentRoute'] ?? '—'}');

  final List<dynamic> flow = screen['userFlow'] as List<dynamic>? ?? <dynamic>[];
  for (final dynamic step in flow) {
    if (step is Map) {
      body.writeln('  • ${step['label']} → ${step['metadata']?['to'] ?? ''} @ ${step['timestamp']}');
    }
  }
  body.writeln();

  final Map<String, dynamic>? triggering =
      network['triggering'] as Map<String, dynamic>?;
  if (triggering != null && triggering.isNotEmpty) {
    body
      ..writeln('API (triggering request)')
      ..writeln('------------------------')
      ..writeln('Method      : ${triggering['method']}')
      ..writeln('Path        : ${triggering['path']}')
      ..writeln('Status      : ${triggering['statusCode']}')
      ..writeln('Trace ID    : ${triggering['traceId']}')
      ..writeln('Waterfall   : ${triggering['waterfallSec'] ?? triggering['waterfallUs']}')
      ..writeln();
  }

  final List<dynamic> recent = network['recent'] as List<dynamic>? ?? <dynamic>[];
  if (recent.isNotEmpty) {
    body.writeln('Recent API calls');
    body.writeln('----------------');
    for (final dynamic item in recent) {
      if (item is Map) {
        body.writeln('  • ${item['method']} ${item['path']} (${item['statusCode'] ?? item['level']})');
      }
    }
    body.writeln();
  }

  final String? stack = event['stackTrace'] as String?;
  if (stack != null && stack.isNotEmpty) {
    body
      ..writeln('Stack trace')
      ..writeln('-----------')
      ..writeln(stack)
      ..writeln();
  }

  body
    ..writeln('—')
    ..writeln(
      'Generated by Scout App Logger (scout_logger). JSON incident attached in backend ingest.',
    );
  return body.toString();
}

String _timeUtc(Map<String, dynamic> incident) {
  final Map<String, dynamic>? time = incident['time'] as Map<String, dynamic>?;
  return time?['utc'] as String? ?? incident['timestamp'] as String? ?? '—';
}

String _timeLocal(Map<String, dynamic> incident) {
  final Map<String, dynamic>? time = incident['time'] as Map<String, dynamic>?;
  return time?['local'] as String? ?? '—';
}

String formatIncidentEmailSubject(
  Map<String, dynamic> incident,
  String prefix,
) {
  final Map<String, dynamic> event =
      incident['event'] as Map<String, dynamic>? ?? <String, dynamic>{};
  final Map<String, dynamic> app =
      incident['app'] as Map<String, dynamic>? ?? <String, dynamic>{};
  return '$prefix ${event['level']} · ${app['packageName']} · ${event['message']}';
}
